# Generated by Django 3.2 on 2023-04-07 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profiles_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCoins',
            fields=[
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.PositiveBigIntegerField(blank=True, default=50, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_profilecoins_objects', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profiles')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_profilecoins_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profilecoin',
                'verbose_name_plural': 'profilecoins',
                'db_table': 'accounts_profilecoins',
                'ordering': ('date_added',),
            },
        ),
    ]
