# Generated by Django 3.2 on 2023-04-07 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_profilecoins'),
        ('programs', '0003_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.DurationField()),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='chiefuser/')),
                ('video', models.FileField(blank=True, null=True, upload_to='courses/')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'db_table': 'programs_lessons',
                'ordering': ('date_added',),
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='chiefuser/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='order_id',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ProfileLesson',
            fields=[
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_profilelesson_objects', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.lessons')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profiles')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_profilelesson_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile lesson',
                'verbose_name_plural': 'profile lessons',
                'db_table': 'programs_profile_lessons',
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='ProfileCourses',
            fields=[
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_activated', models.BooleanField(blank=True, default=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.courses')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_profilecourses_objects', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profiles')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_profilecourses_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile course',
                'verbose_name_plural': 'profile courses',
                'db_table': 'programs_profile_course',
                'ordering': ('date_added',),
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.courses'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_lessons_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessons',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_lessons_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
