# Generated by Django 3.2 on 2023-04-07 18:25

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20230407_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='static/courses/'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='static/lessons_cover/'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/lessons/'),
        ),
    ]
